apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Chart.Name }}-server"
  labels:
  {{- include "teamcity.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
    {{- include "teamcity.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "teamcity.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "teamcity.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.server.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: app
          containerPort: 8111
          protocol: TCP
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        env:
          {{- toYaml .Values.teamcity.server.env | nindent 12 }}
        volumeMounts:
        - name: teamcity-data
          mountPath: /data/teamcity_server/datadir
        - name: teamcity-logs
          mountPath: /opt/teamcity/logs
      volumes:
      - name: teamcity-data
      {{- if .Values.pvc.existingDataPvc }}
        persistentVolumeClaim:
          claimName: {{ .Values.pvc.existingDataPvc }}
      {{- else if .Values.pvc.data }}
        persistentVolumeClaim:
          claimName: {{ .Values.pvc.data }}
      {{- else }}
        emptyDir: {}
      {{- end }}
      - name: teamcity-logs
      {{- if .Values.pvc.logs }}
        persistentVolumeClaim:
          claimName: {{ .Values.pvc.logs }}
      {{- else }}
        emptyDir: {}
      {{- end -}}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end -}}
{{- if and .Values.pvc.data (not .Values.pvc.existingDataPvc) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Values.pvc.data }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
{{- end -}}
{{- if .Values.pvc.logs }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Values.pvc.logs }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
{{- end -}}
