apiVersion: v1
kind: Service
metadata:
  name: {{ include "teamcity.fullname" . }}
  labels:
    {{- include "teamcity.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.ext_type }}
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: app
    name: http
  selector:
    {{- include "teamcity.selectorLabels" . | nindent 4 }}
  sessionAffinity: None