apiVersion: v1
kind: Service
metadata:
  name: "{{ include "teamcity.fullname" . }}-int"
  labels:
    {{- include "teamcity.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.int_type }}
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: app
    name: app
  selector:
    {{- include "teamcity.selectorLabels" . | nindent 4 }}
  sessionAffinity: None